version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:13.9
    # build: .
    ports:
      - '9432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=coworkerdb

    volumes:
      - ./init.d/:/docker-entrypoint-initdb.d/
      - ./postgresql:/var/lib/postgresql/data
  
    